# Generated by Django 5.2.15 on 2026-07-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('paid', 'Оплачене'), ('processing', 'В обробці'), ('shipped', 'Відправлене'), ('done', 'Виконане'), ('canceled', 'Скасоване')], default='new', max_length=16, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує'), ('paid', 'Оплачено'), ('failed', 'Помилка')], default='pending', max_length=16, verbose_name='Оплата')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('shipping_method', models.CharField(blank=True, max_length=128, verbose_name='Доставка')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Адреса')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=64, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('size_label', models.CharField(max_length=64, verbose_name='Розмір')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна/шт')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='ПДВ %')),
                ('price_includes_vat', models.BooleanField(default=True, verbose_name='З ПДВ')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума рядка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
    ]
