# Generated by Django 5.2.16 on 2026-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
