# Generated by Django 5.2.15 on 2026-07-22 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent',
            field=models.CharField(default='#D6AE34', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Accent (жовтий)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_bg',
            field=models.CharField(default='#ECEDEF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Фон сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_border',
            field=models.CharField(default='#DEE2E6', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Бордери'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_catalog_btn',
            field=models.CharField(default='#69BE68', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Кнопка Каталог'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_catalog_btn_text',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Текст кнопки Каталог'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_danger',
            field=models.CharField(default='#D64545', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Акція / знижка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_header_bg',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Фон хедера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_header_top_bg',
            field=models.CharField(default='#314780', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Фон top-bar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_header_top_text',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Текст top-bar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_link',
            field=models.CharField(default='#48A848', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Посилання'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_logo_bg',
            field=models.CharField(default='#69BE68', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Фон логоблоку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary',
            field=models.CharField(default='#69BE68', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Primary (зелений)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary_dark',
            field=models.CharField(default='#48A848', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Primary темний'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_secondary',
            field=models.CharField(default='#314780', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Secondary (синій)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_success',
            field=models.CharField(default='#2E8B57', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Успіх / наявність'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_surface',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Поверхня / картки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_text',
            field=models.CharField(default='#212529', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_text_muted',
            field=models.CharField(default='#6B6666', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Текст вторинний'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_hours',
            field=models.CharField(blank=True, default='цілодобово | без вихідних', max_length=128, verbose_name='Прийом замовлень'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='processing_hours',
            field=models.CharField(blank=True, default='Пн - Пт | 9:00 - 18:00', max_length=128, verbose_name='Обробка замовлень'),
        ),
    ]
