# Generated by Django 5.2.16 on 2026-07-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_theme_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('cta_label', models.CharField(blank=True, default='Перейти в каталог', max_length=128, verbose_name='Кнопка')),
                ('cta_url', models.CharField(blank=True, default='/katalog/', max_length=512, verbose_name='Посилання кнопки')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Hero-слайд',
                'verbose_name_plural': 'Hero-слайди',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ContactsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка — Контакти',
                'verbose_name_plural': 'Сторінка — Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeAdvantagesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCatalogSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Каталог',
                'verbose_name_plural': 'Головна — Каталог',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeNewsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Новини',
                'verbose_name_plural': 'Головна — Новини',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomePromoSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Акції',
                'verbose_name_plural': 'Головна — Акції',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeSeoSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — SEO-текст',
                'verbose_name_plural': 'Головна — SEO-текст',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeServicesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Сервіси',
                'verbose_name_plural': 'Головна — Сервіси',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeTopsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Лідери',
                'verbose_name_plural': 'Головна — Лідери',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал сайту',
                'verbose_name_plural': 'Підвал сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка сайту',
                'verbose_name_plural': 'Шапка сайту',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='brand/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brand/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO description (сайт)'),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('contacts', 'Контакти')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='Підпис')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання'), ('video', 'Відео')], default='text', max_length=16, verbose_name='Тип')),
                ('text_html', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('link_url', models.CharField(blank=True, max_length=512, verbose_name='URL')),
                ('link_label', models.CharField(blank=True, max_length=128, verbose_name='Текст посилання')),
                ('video_embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('video_file', models.FileField(blank=True, upload_to='blocks/video/', verbose_name='Відеофайл')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
    ]
