# Generated by Django 5.2.15 on 2026-08-17 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pickup_and_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_telegram_url',
            field=models.CharField(blank=True, help_text='Повний URL, напр. https://t.me/…', max_length=512, validators=[django.core.validators.URLValidator(message='Вкажіть повний URL (https://… або viber://…)', schemes=['http', 'https', 'viber', 'tg'])], verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_viber_url',
            field=models.CharField(blank=True, help_text='Повний URL, напр. https://invite.viber.com/… або viber://chat?number=…', max_length=512, validators=[django.core.validators.URLValidator(message='Вкажіть повний URL (https://… або viber://…)', schemes=['http', 'https', 'viber', 'tg'])], verbose_name='Viber URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_whatsapp_url',
            field=models.CharField(blank=True, help_text='Повний URL, напр. https://wa.me/380…', max_length=512, validators=[django.core.validators.URLValidator(message='Вкажіть повний URL (https://… або viber://…)', schemes=['http', 'https', 'viber', 'tg'])], verbose_name='WhatsApp URL'),
        ),
    ]
