# Generated by Django 5.2.15 on 2026-07-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay')], default='liqpay', max_length=16, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('created', 'Створено'), ('redirected', 'Перенаправлено'), ('success', 'Успіх'), ('failure', 'Помилка'), ('refunded', 'Повернення')], default='created', max_length=16, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='External ID')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='Request')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіжна транзакція',
                'verbose_name_plural': 'Платіжні транзакції',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx')],
            },
        ),
    ]
