# Generated by Django 5.2.15 on 2026-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Idempotency key'),
        ),
    ]
