# Generated by Django 5.2.15 on 2026-07-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=128, verbose_name='Назва')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Атрибут фільтра',
                'verbose_name_plural': 'Атрибути фільтрів',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('path', models.CharField(db_index=True, max_length=512, unique=True, verbose_name='Шлях')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'L1'), (2, 'L2')], verbose_name='Рівень')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Батьківська')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='Значення')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.facetattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значення фільтра',
                'verbose_name_plural': 'Значення фільтрів',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('standard', models.CharField(blank=True, max_length=64, verbose_name='Стандарт')),
                ('material', models.CharField(blank=True, max_length=128, verbose_name='Матеріал')),
                ('coating', models.CharField(blank=True, max_length=128, verbose_name='Покриття')),
                ('industry', models.CharField(blank=True, max_length=128, verbose_name='Галузь')),
                ('diameter_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ø мін')),
                ('diameter_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ø макс')),
                ('length_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='L мін')),
                ('length_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='L макс')),
                ('is_top', models.BooleanField(default=False, verbose_name='Топ')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акція')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_groups', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to='catalog.category', verbose_name='Категорія L2')),
            ],
            options={
                'verbose_name': 'Товарна група',
                'verbose_name_plural': 'Товарні групи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('file', models.FileField(upload_to='product_docs/', verbose_name='Файл')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.productgroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Документ товару',
                'verbose_name_plural': 'Документи товарів',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='collections', to='catalog.productgroup', verbose_name='Товарні групи')),
            ],
            options={
                'verbose_name': 'Підбірка',
                'verbose_name_plural': 'Підбірки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Головне')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productgroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Назва (з розміром)')),
                ('size_label', models.CharField(max_length=64, verbose_name='Розмір')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Діаметр')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Довжина')),
                ('thread_pitch', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Крок різьби')),
                ('strength_class', models.CharField(blank=True, max_length=32, verbose_name='Клас міцності')),
                ('min_party', models.PositiveIntegerField(default=1, verbose_name='Мін. партія')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення')], default='in_stock', max_length=16, verbose_name='Наявність')),
                ('stock_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість на складі')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна за шт')),
                ('price_includes_vat', models.BooleanField(default=True, verbose_name='Ціна з ПДВ')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ставка ПДВ %')),
                ('party_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна партії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='catalog.productgroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'ordering': ['diameter', 'length', 'article'],
            },
        ),
        migrations.CreateModel(
            name='SKUFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='catalog.productsku', verbose_name='SKU')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_links', to='catalog.facetvalue', verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Facet SKU',
                'verbose_name_plural': 'Facets SKU',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='catalog_category_parent_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='facetvalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='catalog_facetvalue_attr_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='productgroup',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_5875c2_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['group', 'is_active'], name='catalog_pro_group_i_c56e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['diameter', 'length'], name='catalog_pro_diamete_064982_idx'),
        ),
        migrations.AddConstraint(
            model_name='skufacet',
            constraint=models.UniqueConstraint(fields=('sku', 'value'), name='catalog_skufacet_sku_value_uniq'),
        ),
    ]
