# Generated by Django 5.2.15 on 2026-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facetvalue',
            options={'ordering': ['sort_order', 'value'], 'verbose_name': 'Значення фільтра', 'verbose_name_plural': 'Значення фільтрів'},
        ),
        migrations.AddField(
            model_name='facetvalue',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
