# Generated by Django 5.2.16 on 2026-07-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_facetvalue_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportExport',
            fields=[
            ],
            options={
                'verbose_name': 'Імпорт / експорт',
                'verbose_name_plural': 'Імпорт / експорт',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.productsku',),
        ),
    ]
