# Generated by Django 5.2.16 on 2026-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog_import_export_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='facetvalue',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=128, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
