# Generated by Django 5.2.16 on 2026-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='image',
            field=models.ImageField(blank=True, help_text='Формат 4:3, рекомендовано 1200×900 px (JPEG/PNG/WebP). Якщо співвідношення інше — фото автоматично обрізається по центру під 4:3 і масштабується до 1200×900.', upload_to='sku/', verbose_name='Фото SKU'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Формат 4:3, рекомендовано 1200×900 px (JPEG/PNG/WebP). Якщо співвідношення інше — фото автоматично обрізається по центру під 4:3 і масштабується до 1200×900.', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
