# Generated by Django 5.2.16 on 2026-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productsku_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='party_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Необовʼязково. Якщо задана — застосовується при qty ≥ мін. партії.', max_digits=12, null=True, verbose_name='Ціна опт (партія)'),
        ),
    ]
