# Generated by Django 5.2.15 on 2026-08-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productsku_party_price_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='bore_d_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Підшипники: внутрішній діаметр d. Можна змінити вручну.', max_digits=8, null=True, verbose_name='Внутрішній діаметр (мм) d'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='od_d_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Підшипники: зовнішній діаметр D. Можна змінити вручну.', max_digits=8, null=True, verbose_name='Зовнішній діаметр (мм) D'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='width_b_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Підшипники: ширина B. Можна змінити вручну.', max_digits=8, null=True, verbose_name='Ширина (мм) B'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['bore_d_mm', 'od_d_mm', 'width_b_mm'], name='catalog_pro_bore_d__488913_idx'),
        ),
    ]
