# Generated by Django 5.2.15 on 2026-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productsku_bearing_dims'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='head_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Автосаморізи: третє число в розмірі «довжина × діаметр × ширина головки» (напр. 24×4,2×7,6). Заповнення вручну.', max_digits=8, null=True, verbose_name='Ширина головки (мм)'),
        ),
    ]
