# Generated by Django 5.2.15 on 2026-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productsku_head_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='cell_a_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Композитна сітка: перше число ячейки (напр. 10 у 10×10).', max_digits=8, null=True, verbose_name='Ячейка A (мм)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='cell_b_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Композитна сітка: друге число ячейки (напр. 200 у 200×200).', max_digits=8, null=True, verbose_name='Ячейка B (мм)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Клинки: товщина.', max_digits=8, null=True, verbose_name='Товщина (мм)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Клинки: ширина. Разом з довжиною і товщиною.', max_digits=8, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
