# Generated by Django 5.2.15 on 2026-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productsku_composite_dims'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='application_zone',
            field=models.CharField(blank=True, choices=[('internal', 'Внутрішні роботи'), ('external', 'Зовнішні роботи'), ('both', 'Внутрішні та зовнішні')], help_text='Піни / клеї / герметики: внутрішні / зовнішні роботи.', max_length=16, verbose_name='Зона застосування'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Піни / клеї / герметики: назва виробника на SKU.', max_length=128, verbose_name='Виробник'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='pack_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Піни / клеї / герметики: кількість штук в оптовій упаковці.', null=True, verbose_name='Шт в упаковці'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Піни / клеї / герметики: обʼєм у мілілітрах.', max_digits=10, null=True, verbose_name='Обʼєм (мл)'),
        ),
    ]
